### ISSUE TITLE
Reduce image size

### ISSUE THREAD

**Issue by cesarvr** [bucharest-gold/centos7-s2i-nodejs#20]
Just a suggestion what do you think of looking for ways to reduce the images size. 
I think it can be cool to have images sizes similar [alpine-node](https://github.com/mhart/alpine-node) they get sizes of ≈40MB.  If we have that, it can dramatically increase deploy speed and transfer between node's. 

- I think we can create maybe a strip down Centos7 (139 MB) image. just leaving there dnf(package manager) and the native libraries required by nodejs (libc, libstdc++, xz, tar, wget) thats it :) 

any thoughts ? 
Thanks.

**Comment by lance** [comment]
Our image extends the base image `openshift/base-centos7`, which itself is 139MB compressed. We add 27MB to it to create a 166MB image. Which is essentially the size of node+npm and that's about it.

So you are right to say that stripping down the image would be good, but that means it will either need to happen as an upstream pull request on https://github.com/sclorg/s2i-base-container which is the repository that creates these base images, or we need to look elsewhere for a base image.

I poked around a little and found the `Dockerfile` for `openshift/base-centos7` [here](https://github.com/sclorg/s2i-base-container/blob/master/base/Dockerfile). As you can see, it adds a lot of stuff, but as I dig through it, and think about the work that any s2i image does, it seems there's not much that could be eliminated. Remember, Node.js apps may have native dependencies, and these need to get built by the s2i image during `npm install` on creation of the output image. So we have to have things like `gcc-c++` in these builder images.

This image, as you can see, extends [`centos7/s2i-core-centos7`](https://hub.docker.com/r/centos/s2i-core-centos7/tags/), which is only about 80MB. So the stuff being installed by `openshift/base-centos7` is about 50MB or so compressed.

I'm not sure how much space each of the installed packages require, and I'm not sure which ones are definitively needed for Node.js native modules. But as a quick back of the napkin sketch, here are a couple of things that might be removed:

https://github.com/sclorg/s2i-base-container/blob/aea49ecd81acdc3efdbc0149e461bdeea900817e/base/Dockerfile#L36-L37

https://github.com/sclorg/s2i-base-container/blob/aea49ecd81acdc3efdbc0149e461bdeea900817e/base/Dockerfile#L40-L42

And yes, using `dnf` instead of `yum` will probably reduce the image size as well.

We could potentially make our s2i image `FROM centos7/s2i-core-centos7`, then use `dnf` instead of `yum`, duplicates most of what's in `openshift/base-centos7`, but eliminates some of these seemingly unnecessary packages. I'm not sure how much that would reduce the size. At the moment, this is a bit of a low priority for me, but if you would like to submit a pull request, I'd be happy to take a look.

**Comment by cesarvr** [comment]
Awesome, I will take a look to see if the size can be reduced.

**Comment by lance** [comment]
@cesarvr I also found information about "chained builds" in the [openshift documentation](https://docs.openshift.org/latest/dev_guide/builds/advanced_build_operations.html#dev-guide-chaining-builds). Using this would allow us to have both a builder image (our current centos7-s2i-nodejs image), and a runtime image that is considerably smaller.

The s2i image would be responsible for creating the runtime artifact - essentially the application source after `npm install` has been run. And the second, chained builder image would be a stripped down image with only runtime essentials and the application itself installed.

Both paths of effort are useful, but this could be a better long-term strategy, perhaps.

**Comment by cesarvr** [comment]
Hi @lance , I was having some fun and try to do my own image from scratch so I create this one [cvaldezr/fedora-example](https://hub.docker.com/r/cvaldezr/fedora-example/tags/) (Fedora26). 
If you want to give it a try just clone the current project and change the base image to point to cvaldezr/fedora-example and execute `docker build --build-arg NODE_VERSION=6.11.2 -t sti-node-light .`, so you can test, for now Clang is not included for now. 

final container: 
centos/sti => 470 MB 
[cvaldezr/fedora-example](https://hub.docker.com/r/cvaldezr/fedora-example/tags/)  => 197MB 

I think there are still room for improvement :) 

the "chained builds" in OSE is something I didn't know but seems as the way to go achieve very thin final containers, but also, maybe it can take away the simplicity of S2i, not sure.

**Comment by lance** [comment]
With the move towards using our own base image, this task has become somewhat irrelevant
