### ISSUE TITLE
Enable OpenShift Debugging

### ISSUE THREAD

**Issue by rhoads-zach** [bucharest-gold/centos7-s2i-nodejs#33]
Enable a debugger to attach to a node.js application running in OpenShift.

ATM, you can set the following environment variables:
* DEV_MODE=true
* NODE_ENV=development

which will provide some access over 5858, but you should consider a different solution.

**Comment by lholmquist** [comment]
Ok, so at some point i was able to remote debug my application running on openshift in the chrome debugger, so i set out to remember how to do it.

I had originally used the openshift-test repo, https://github.com/lance/openshift-test.

deployed that openshift in debug mode

The end of the log of the pod looked sort of like this: 

```

+ echo 'Launching via nodemon...'
--
  | + exec npx nodemon --inspect=5858
  | Launching via nodemon...
  | [nodemon] 1.17.3
  | [nodemon] to restart at any time, enter `rs`
  | [nodemon] watching: *.*
  | [nodemon] starting `node --inspect=5858 index.js`
  | Debugger listening on ws://127.0.0.1:5858/545f2720-8d15-4e0a-87d0-c4eec871905b
  | For help see https://nodejs.org/en/docs/inspector
  | Server listening on port 8080


```

Then from console, i did this: 
`oc port-forward $(oc get po | grep openshift-test | grep Running | awk '{print $1}') 8888:5858`

Then went to `chrome://inspect` in the browser, clicked "configure" and added `127.0.0.1:8888` and was able to remote debug.


I wanted to recreate that with a booster, so i took the configmap booster,  https://github.com/bucharest-gold/nodejs-configmap, and did the normal deploy stuff, but made sure it was in debug mode using "--build.env NODE_ENV=debug"

The end of the pod log for that is similar to this:

```

npm info ok
--
  | + echo 'Launching via nodemon...'
  | + exec npx nodemon --inspect=5858
  | Launching via nodemon...
  | [nodemon] 1.17.3
  | [nodemon] to restart at any time, enter `rs`
  | [nodemon] watching: *.*
  | [nodemon] starting `PORT=8080 node ./bin/www --inspect=5858`
```

Now, when i try to port forward, i keep getting an error about a connection refused, sort of like this:

```
Handling connection for 8888
Handling connection for 8888
E0418 20:37:32.844331   72361 portforward.go:331] an error occurred forwarding 8888 -> 5858: error forwarding port 5858 to pod 12f4b2e7dbc0830d237f8e2418c561047951bcc73f7f4ce120db174fd2420b89, uid : exit status 1: 2018/04/18 20:37:32 socat[5398] E connect(5, AF=2 127.0.0.1:5858, 16): Connection refused
E0418 20:37:32.848624   72361 portforward.go:331] an error occurred forwarding 8888 -> 5858: error forwarding port 5858 to pod 12f4b2e7dbc0830d237f8e2418c561047951bcc73f7f4ce120db174fd2420b89, uid : exit status 1: 2018/04/18 20:37:32 socat[5399] E connect(5, AF=2 127.0.0.1:5858, 16): Connection refused
```


I think i know why,  in the second example, the debugger is never listening since the "--inspect=5858" is in the wrong spot when starting the node process.

Not sure how to fix that.  I'll check in the nodemon issues

**Comment by lholmquist** [comment]
might be a possible solution  https://github.com/remy/nodemon/issues/1226

**Comment by lance** [comment]
@lholmquist are you sure you don't need to expose that port as a route?

**Comment by lance** [comment]
Ahh - I think you are right @lholmquist - specifically this comment in that issue

> I believe that if you change your package so that the main prop reads ./bin/www, and change scripts.start to node . you should be able to pass --inspect to nodemon the way you're expecting to.

**Comment by lholmquist** [comment]
that almost worked,  I added the main section with "./bin/www" and my scripts.start is not "PORT=8080 node ."

but it looks like nodemon is stripping of that PORT part for some reason.  
```

Launching via nodemon...
--
  | + echo 'Launching via nodemon...'
  | + exec npx nodemon --inspect=5858
  | [nodemon] 1.17.3
  | [nodemon] to restart at any time, enter `rs`
  | [nodemon] watching: *.*
  | [nodemon] starting `node --inspect=5858 ./bin/www`
  | Debugger listening on ws://127.0.0.1:5858/349faca7-9d6e-4f66-ae7c-29afe9eeefcb
  | For help see https://nodejs.org/en/docs/inspector


```

almost there.

with this new setup, if i do a "npm run start" locally, things are working,

**Comment by lholmquist** [comment]
It looks like this is expected behavior for nodemon.  from what i've seen, if you want to add an environment variable during the nodemon execution, you do something like `PORT=8080 nodemon`

So there are a couple things we can do for the boosters to add the PORT env variable.

1. change the default port in the "./bin/www" file to 8080 instead of 3000 - https://github.com/bucharest-gold/nodejs-configmap/blob/master/bin/www#L35
   * This is the quickest option

2. in the deployment config, create an environment variable 
    * This could also be added to the deploymentConfig "enricher" so a user wouldn't have to specify it if they were just letting nodeshift create a default deploymentConfig for them
    * This might be a better option in the long run? 

I do need to update all the boosters to include a "main" property and change the start script to what i showed in the previous post.  So i will need to update the boosters no matter what
